#!/usr/bin/perl

opendir(DIR, "Assets/Editor");
@files = grep(/PostprocessBuildPlayer_\d*/,readdir(DIR));
closedir(DIR);

foreach $file( @files ){
	print "PostProcessBuildPlayer: calling " . $file . "\n"; 
	system("Assets/Editor/".$file, $ARGV[0], $ARGV[1], $ARGV[2], $ARGV[3], $ARGV[4], $ARGV[5], $ARGV[6]); 
} 
